### 课程查询接口
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStutas": "202004",
  "courseName": "",
  "publishStutas": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "测试标签",
  "grade": "204001",
  "description": "课程介绍测试",
  "charge": "201001",
  "price": "",
  "originalPrice": "",
  "qq": "3213444",
  "wechat": "3213444x",
  "phone": "13213444",
  "validDays": 365
}

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes
Content-Type: application/json

### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 [点击修改]"
}

###
