### 课程查询接口
POST {{content_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStutas": "202004",
  "courseName": "",
  "publishStutas": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes


### 新增课程接口
